#define TK_ADD 1
#define TK_SUB 2
#define TK_MULT 3
#define TK_DIV 4
#define TK_MOD 5
#define TK_EXP 6
#define TK_NUM 7
#define TK_ID 8
#define TK_STRING 9
#define TK_CHAR 10
#define TK_PRINT 11
#define TK_PAR_LEFT 12
#define TK_PAR_RIGHT 13
#define TK_EOF 998
#define TK_ERROR 999