#define OP_ADD 1
#define OP_SUB 2
#define OP_MULT 3
#define OP_DIV 4
#define PAR_LEFT 5
#define PAR_RIGHT 6
#define LIT_NUM 7
#define TK_EOL 8
#define TK_EOS 10
#define TK_ID 11
#define OP_ASG 12
#define TK_ERROR 999